Game logic
luciano-ilha/Tic-Tac-Toe pull request #3
Opened 2020-07-07 13:58 UTC by paulzay

### What does this PR do?
Create the logic of the game
### Description of tasks to be completed?
1. Separate logic into different classes
2. Work on edge cases for the game
3. Make the game run

2020-07-07 19:24 UTC, Dandush03 reviewed
# Status 🔴 Required Change 🔴 

### Great Work on your first attempt. but there is some issue we need to attend before moving to your next milestone. 

### Before getting into your code, let me comment on some main issue your facing right now.
- [x] The only place there should be any `puts`, `print `or `get.chump` should be in your main.rb file
> notice how on your board.rb file there is mainly `puts` methods 
> same issue repeat on your game.rb file
- [x] You have hardcoded the winning cases for the first player and second player, please make a method that would wrap both cases without repeating code 
- [x] When I input a negative value it marks it as a valid move

## [__OPTIONAL__]
Add some numeration inside of your bard so people would know which are the available move

## Happy Coding 💻

2020-07-09 23:01 UTC, adaorachi commented
### Hi @paulzay and @luciano-ilha :wave:

I really commend the effort you have put into this project. The game behavior for your project work very well, however there are still some mandatory requirements that it has not met yet and which was requested in the previous review.
Your project will need to pass those requirements in order to be approved.

So, hang in there, you are almost there! :muscle: 

---
### CHANGES REQUIRED :recycle: 

---

- [ ] You still have some `puts/print/chomp` statements in `game.rb` and `board.rb` logic files. Kindly ensure that there is **NO** `puts/print `and `get.chomp` outside main.rb file. Here is the [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from Pathright for more clarification.
You should consider making those methods return a value and call them in the `main.rb` file, and depending on the value you want it to return, you can output your `puts/chomp` statements or not.

2020-07-09 23:02 UTC, adaorachi requested changes

2020-07-09 23:02 UTC, adaorachi commented on lib/game.rb
> +  end
- [x] Kindly avoid the use of global variable, ie - `$player_start, $player_next = switch_players, $not_the_end`. It is NOT recommended because its value can be mutated or overwritten from outside the class. They can be set to anything. 
Meanwhile, you already have those variables set in the attr_reader and which are not useful since you already set them as global variables. You should make those variables useful in the attr_reader by changing them to class instances. 
Also remember to call them appropriately in the `main.rb` file

2020-07-09 23:02 UTC, adaorachi commented on lib/game.rb
> +    end
- [x] You should ensure to use the DRY rule here and avoid repetition of codes. Instead of hard-coding the `markers or player_icons`, you should create a method which will call the marker in that method's arguments. Something similar to this; 

```
 def check_win(player_icon)
    all_equal(board[0..2], player_symbol) ||
    all_equal(board[3..5], player_symbol) ||
    all_equal(board[6..8], player_symbol)
  end
```
...where `all_equal` is also a method that checks if the the markers in that row are the same and if the marker is equal to the current_player's marker.
This is only checking for the rows. The columns and diagonals can be done in a similar way.

2020-07-09 23:03 UTC, adaorachi commented
The requirement below is optional but it would be nice if you take some time to implement it.
- [**optional**] You should consider validating the player's name input to ensure they actually inputted something and not an empty value before they can continue the game. It does not output any error but It would really improve the user-interface.

---

### **After implementing the mandatory changes above, you can request for another code review by submitting a code review form. **
**_Note: All requirements NOT marked with optional are MANDATORY_**

---

Should you have any question, feel free to reach out to me on Slack with the username - **@adaorachi**

Happy Coding :relaxed: 

**MaryAnn Chukwuka**

2020-07-13 18:45 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-07-13 18:53 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **Congratulations TEAM**, you have done a great job implementing all the changes pointed by the previous TSE's :100: Now the project meets all the minimum requirements :slightly_smiling_face: 

[OPTIONAL]
Kindly add instructions on how to clone and run the project in the README file
A screenshot in the README is not a bad idea, we can add it

You can go ahead and merge into development :+1: 
_Happy coding_ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-07-14 08:24 UTC, merged